image:
  file: Dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
  command: >
    git clone git@github.com:drupal-graphql/drupal-decoupled-app.git
  command: >
    docker-compose build
  command: >
    docker-compose up -d
  command: >
   docker-compose exec cli bash
   composer install
   drush si config_installer -y --account-name=admin --account-pass=admin
